### ISSUE TITLE
handling of sequences with more than 30 amino acids

### ISSUE THREAD

**Issue by tobigithub** [kusterlab/prosit#10]
The current code as defined in prosit/prosit/constants.py only supports sequences with up to 30 amino acids.

A total of 81194 sequences exist in the human fast file. Only 703 sequences are smaller than 30 amino acids in the human fast file. 80491 sequences are larger than 30 amino acids. Basically 99.13% of the sequences in humans are not covered with the current prosit code version. 

The error handling could be improved by stating that "only sequences with up to 30 amino acids are supported in prosit" instead of  the rather cryptic error message "index 30 is out of bounds for axis 1".

Maybe it is even possible to just increase the sequence length in constants.py to 34475 letters, which is the longest sequence in the human fasta file? Not sure how that influences predictive accuracy or if that is possible. 

Basically the current error message is not very descriptive for practitioners.  

````
Traceback (most recent call last):
  File "jump.py", line 26, in <module>
    tensor = tensorize.peptidelist(df)
  File "/root/prosit/tensorize.py", line 56, in peptidelist
    "sequence_integer": get_sequence_integer(df.modified_sequence),
  File "/root/prosit/tensorize.py", line 42, in get_sequence_integer
    array[i, j] = constants.ALPHABET[s]
IndexError: index 30 is out of bounds for axis 1 with size 30
````
Example sequences with 30 and 30 letters
````
NGGRDYALRGPEHPGSGGAPEPQGWIHFI
MNERREQLRAKRPEVPFPEITRMLGNEWS
DKRQNSSRFSASNNRELQKLPSLKGPPTL
MVKLTAELIEQAAQYTNAVRDRELDLRVS
MYVAESTRKTLLYHMEFSELTSRYIKIIN
MDFVAGAIGGVCGVAVGYPLDTVKGLLALP
MTGELEVKNMDMKPGSTLKITGSIADGTDG
MEPEFLYDLLQLPKGVEPPAEEELSKGVCP
MEDALFLRKSPPYIFSPIPFLGHAIAFGKS
MSDILRELLCVSEKAANIARACRQQEALFQ
````

**Comment by gessulat** [comment]
`IndexError: index 30 is out of bounds for axis 1 with size 30` 
An index of 30 indicates a amino acids with at least 31 amino acids (zero-based counting).

The reason why we do not include longer amino acids are addressed in detail in our paper. In short, we want to rely on high-quality measurements of synthetic peptides, and there is not enough data to meaningfully train a model.

**Comment by tobigithub** [comment]
@gessulat 
ok, so creating smaller sequences via in-silico digestion.
Do you have a tool for in-silico digestion that you can recommend, like peptidecutter?
So how do I take a fasta file and prep it for prosit? Online?
I feel there is a lot of information missing in the readme or project WIKI.

**Comment by gessulat** [comment]
Internally I am using [pyteomics FASTA digest](https://pyteomics.readthedocs.io/en/latest/examples/example_fasta.html) and other folks use available R libraries. We are working on including a FASTA digest option at our online tool, but the release date is not clear yet. See www.proteomicsdb.org/prosit/

If you are missing any specific information in the readme or wiki please feel free to contribute.
