### ISSUE TITLE
prosit prediction benchmark

### ISSUE THREAD

**Issue by tobigithub** [kusterlab/prosit#12]
Not an issue, just nice to know how prosit performs during predictions. 

**Quick take home:**
- prosit requires TF, Kreas and cuDNN and one GPU, predictions can not be made on CPU only
- increasing batch size for prediction to 10k does not affect run time
- adding multiple GPUs will not improve prediction run times
- time difference between a 1080Ti and a new 2080Ti is minimal
- the GPU during predictions is mostly (90%) idle
- only one single CPU core is used all the time during predictions
- on a modern GPU/CPU, one million tryptic peptides takes around 15 minutes to process
- predicted spectral output file size for one million peptides is 786 Mbyte large
- predictions for 560,296 peptides and their 19 million tryptic digests would take 5 hours
- the fastest consumer CPU for predictions would be a Intel Core i9-9900KF @ 3.60GHz

**Used configuration:**
CPU: Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz (8 core, 16 threads)
GPU: NVIDIA GeForce RTX 2080Ti (11 GB memory)
Model: weight_32_0.10211.hdf5

**Prosit prediction** command for 1 million peptides:
````
~/prosit$ curl -F "peptides=@examples/prosit-1million.csv" http://127.0.0.1:5000/predict/ > msms-prosit-1million.csv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  806M  100  785M  100 20.7M   872k  23571  0:15:22  0:15:22 --:--:--  181M
````

**CPU htop**, only one single core running full time
![image](https://user-images.githubusercontent.com/2569565/60060732-ef988b00-96a6-11e9-99f0-8cc2769eb241.png)

**GPU**, First 1 minute full P2 energy use and utilization of all memory
````
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0  On |                  N/A |
| 31%   55C    P2   239W / 250W |  10736MiB / 10988MiB |     87%      Default |
+-------------------------------+----------------------+----------------------+
````

**GPU**, from 2 to 15 minutes, no GPU utilization, only CPU single core
````
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0  On |                  N/A |
| 29%   37C    P8     2W / 250W |  10736MiB / 10988MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
````
Tobias

**Comment by gessulat** [comment]
Thank you for the benchmarks. 

Some of the points do not match our experience. For example, CPU should not have a huge influence as those mostly govern I/O. Using SSDs or holding as much as possible in RAM for example may speed up the process substantially. When we benchmark only the prediction we see a clear benefit from faster GPUs and higher batch sizes. The supplement [from our paper](https://www.nature.com/articles/s41592-019-0426-7) has a benchmark on speed as well (Supplemental Figure 11).

In general, please keep the Github issues for issues or questions with Prosit (i.e. errors, requests for clarifications) and consider pull requests or wiki entries for general comments. Thank you for sharing your results with us!

**Comment by tobigithub** [comment]
> Some of the points do not match our experience. For example, CPU should not have a huge influence as those mostly govern I/O. Using SSDs or holding as much as possible in RAM for example may speed up the process substantially. When we benchmark only the prediction we see a clear benefit from faster GPUs and higher batch sizes. 


The prediction is clearly single threaded, once this runs on 100% on a thread there is no I/O bottleneck. Otherwise the CPU would run 50% or less, then its clearly I/O. The 2080TI is faster than the 1080TI, no substantial difference. Then the fact (or elephant in the room) that the GPU is only fully utilized during the first 5% of the run, that's really interesting. So maybe that's the limiting step, because export is single threaded, basically it can not export the data fast enough. If the prediction would be actually multi-threaded on the CPU level then you still would have to stitch the results together and then the export could be potentially I/O limited. Overall nothing to worry about, predictions are very fast.

**Comment by tobigithub** [comment]
The new version after July 3rd with MS/MS and RT prediction utilized CPU much better, 50-60% of all threads are active. GPU use is still not observed after initial spike. 800k tryptic digests use with 20 Mbyte size use 20 Gbyte RAM during processing and finishes in 1 hour.

So the functionality for multiple and effective GPU predictions is also currently missing.
https://stackoverflow.com/questions/42409884/keras-tensorflow-prediction-on-multiple-gpus?rq=1
and
https://stackoverflow.com/questions/44255362/tensorflow-simultaneous-prediction-on-gpu-and-cpu

**Comment by gessulat** [comment]
The CPU load you are seeing, comes from transforming the csv file into suitable numpy arrays and back. The prediction utilizes the GPU.

Currently, prediction speed is not a bottleneck that is why multi-gpu support is not high on our priority list. Pull requests are very welcome though :)

**Comment by tobigithub** [comment]
@gessulat 
"pull requests" I wish, but its not my domain. If I would I'd probably focus on:

1) maybe some native deployment of the prosit code so it could run under Windows. Basically without the Docker skeleton (which is great, but not working under WIN due to GPU pass-through)
2) maybe some code that would do the **prosit predictions** just on the CPU (n=44 or 56)
without the requirement to install GPU dependencies, with tf.device('/cpu:0')?
3) maybe some general benchmarks so we can saturate the CPU with use of ramfs/tmpfs
for large(er) memory machines 100 to 500 GByte
4) maybe some prediction benchmarks that show use of a single/multiple GPUs is actually faster,
but as you mentioned the Keras/TF code is quite complicated

Overall I agree, for people working on a single genome or organism the calculations are quite fast,
running all uniprot with all major digestion methods under 2-3 CID voltages might cover all important experiments. Then one would need to calculate that once and store in a database. No need to recalculate. Basically a google for prosit CID MS/MS and RT predictions, much faster of course.
