### ISSUE TITLE
Web site spectral library generation - cysteine residue mass

### ISSUE THREAD

**Issue by karlssoc** [kusterlab/prosit#13]
Hi,
I have generated a Prosit spectral library via https://www.proteomicsdb.org/prosit/ and compared the synthetic library (in spectronaut format) to a DDA/OpenSwathWorkflow-based counterpart (n ~5500 peptides).

For most peptides with modifications (oxidized methionine or carbamidomethylation)  the PrecursorMz for the Prosit version is lower than OpenSwath. The most common delta PrecursorMz of OpenSwath - Prosit when considering peptide charge state is 57.02. It appears as the web service is not considering all C as treated C with carbamidomethylation. 

I am not sure if this is an issue or if I misunderstood something.

An example:

**OpenSwath**
ADC(UniMod:4)VQTLLLNQQR, PrecursorCharge 2
779.9039
ADC(UniMod:4)VQTLLLNQQR, PrecursorCharge 3
520.2717

**Prosit**
_ADC[Carbamidomethyl (C)]VQTLLLNQQR_,  PrecursorCharge 2
751.3932
_ADC[Carbamidomethyl (C)]VQTLLLNQQR_, PrecursorCharge 3
501.2646

https://www.proteomicsdb.org/prosit/task/E62AFBA12ECBF8F4FEAF3D0D530A31BF

Thanks,
Christofer

**Comment by tkschmidt** [comment]
Thanks for the notice. You were/are completely right and I made a small mistake at the precursor calculation step (just for the csv format). The fragment masses were **not** affected by that.  
I pushed a new version of our website right now and it looks right, could you check if it is fine for you as well?

**Comment by karlssoc** [comment]
Thanks! The problem is resolved: I generated a second version of library today and the delta-PrecursorMz:s are now ranging between -0.000072549 to 0.000061701.

**Comment by tobigithub** [comment]
@karlssoc 
good catch. tnx!

**Comment by jmueller95** [comment]
Hey all,
is it possible that this has only been resolved in the online version of Prosit, but not in the version in this git repo? I just started using it today, and for any peptide that contains C, the precursor m/z seems to be too small. E.g. for 3+ charged "AAALLCQLLL", the precursor m/z is reported as 
343.543939, however, if the Cysteine is carbamidomethylated, I believe it should be around 362.54398. Since it's my first time using Prosit, I might be misunderstanding something, though.

Best wishes,
Julian

**Comment by tobigithub** [comment]
@jmueller95 Could be, maybe run 10-20 relevant molecules and compare? Its all about validation.

**Comment by jmueller95** [comment]
@tobigithub Thanks for the fast reply! I ran some peptides containing Cysteine and calculated unmodified and C+57 precursor m/zs for each of them ([peptides_w_cysteines.txt](https://github.com/kusterlab/prosit/files/4414004/peptides_w_cysteines.txt)). The m/z reported by Prosit always agrees with the unmodified m/z, even though the fragment m/zs account for the mass shift.

**Comment by tkschmidt** [comment]
hey, we will investigate
