### ISSUE TITLE
Submitted 42 peptides at 12PM, Jun. 28, 2019. The task is still in progress.

### ISSUE THREAD

**Issue by fcyu** [kusterlab/prosit#15]
I would like to ask if it is normal? Is there something wrong with my peptides?

Here is the peptides.
[test.zip](https://github.com/kusterlab/prosit/files/3342912/test.zip)

Thanks,

Fengchao

**Comment by gessulat** [comment]
We sometimes have to restart the server for updates. Have you tried resubmitting your task?
Usually it should not take that long.

**Comment by fcyu** [comment]
Yes, I submitted another one (containing 12 peptides) at 9:44AM, Jun. 29, 2019. It is also still in progress.

Here is the peptides.
[test2.zip](https://github.com/kusterlab/prosit/files/3342995/test2.zip)

The Task IDs are AA5297342BF3975CE21F9A902D90F239 and 41D7EFEC91F463B71CF3DAB01CC6680D, respectively.

Thanks,

Fengchao

**Comment by tobigithub** [comment]
@fcyu 
There are probably tons of people using the web version (online prediction tool).
But just use the local version, its quite performant, no need to use the web version.
19 million peptides can be predicted in 5:48h on a single GPU and single CPU. [#12]

**Comment by tkschmidt** [comment]
@fcyu thanks for telling us. Queueing is hard, a small lock happened, but your jobs are done now.
