### ISSUE TITLE
Predicted iRTs are concentrated within a very narrow range

### ISSUE THREAD

**Issue by younglululu** [kusterlab/prosit#17]
I tried to use Prosit to predict iRTs. The reference proteomes I used contains Human, Ecoli and Yeast (Navarro dataset). The peptides I used for testing are of size ~5M, of length [7,30]. I use both Prosit and DeepRT(+) to predict the RT, with the default parameter setting.

However, I observed that the predicted iRT from Prosit is very concentrated to a very small range around 56. I am wondering if I was doing something wrong. 

![prosit_vs_deeprt](https://user-images.githubusercontent.com/15314522/61151220-4e794500-a49a-11e9-999c-0ad6b6e890e2.png)

**Comment by gessulat** [comment]
Are you comparing retention times from DeepRT directly with iRT predictions from Prosit? If so, you probably have to interpolate the iRT values to "real" RT.

@tkschmidt is our expert on retention time, maybe he has some idea.

**Comment by tobigithub** [comment]
Hi,
@younglululu, good catch, always good to validate anything and everything. 

I get the same results when the current Prosit github code (Latest commit 85e2d97) and the published prosit models on [Figshare](https://figshare.com/projects/Prosit/35582) from 30/11/2018. The RTs from 56.0 to 56.7 do not make sense.

![image](https://user-images.githubusercontent.com/2569565/61671706-a2a3d680-ac9d-11e9-8d08-c0bf91ad6a39.png)

![image](https://user-images.githubusercontent.com/2569565/61671741-ccf59400-ac9d-11e9-96b5-77ca0d575d03.png)


The prosit paper reports scaled  iRTs from -100 to 200 units. See [Prosit Supplement PDF ](https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-019-0426-7/MediaObjects/41592_2019_426_MOESM1_ESM.pdf). If you use the prosit online service, you will get iRT data like that, which is similar to the supplement informatio: 

![image](https://user-images.githubusercontent.com/2569565/61671507-cdd9f600-ac9c-11e9-9583-b0a0f81a5230.png)

So four things:
1) Could be an issue with the code (scaling or config) find [scal](https://github.com/kusterlab/prosit/search?q=scal&unscoped_q=scal)
2) Could be an issue with the iRT model.
3) Could be an issue with keras or tensorflow
4) Always use the online server with small input sets to validate everything from local prosit github installations.
5) Should be easy to figure out, if the github code and input models are the same like the online prosit webserver.

**Comment by tkschmidt** [comment]
will investigate

**Comment by tkschmidt** [comment]
issue is resolved, @gessulat will merge it in a second.

**Comment by tobigithub** [comment]
@gessulat @tkschmidt @younglululu 
Tnx.

**Comment by younglululu** [comment]
Thanks! The problem has been solved and here is the new comparison between Prosit and DeepRT:

![Figure_1](https://user-images.githubusercontent.com/15314522/62086611-c2924780-b213-11e9-8d07-ddf4ea623306.png)

**Comment by tobigithub** [comment]
@younglululu 
a) How about Prosit vs SSRCalc?
b) and SSRCalc vs DeepRT?
c) What are the sequences that are separated from -10 to 200 in Prosit, but only elute between 5 and 25 in DeepRT (the leg or base of your figure). Prosit seems to know something about those and separates them, while DeepRT just squishes them together. So this culprit needs to be investigated.

http://hs2.proteome.ca/SSRCalc/SSRCalcX.html
http://hs2.proteome.ca/SSRCalc/SSRCalcQ.html

Also the [prosit paper](https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-019-0426-7/MediaObjects/41592_2019_426_MOESM1_ESM.pdf) only mentions SSRCalc.
