### ISSUE TITLE
Runing Error

### ISSUE THREAD

**Issue by lkytal** [kusterlab/prosit#2]
Error when trying to do prediction, seems like the graph is disconnected? Clone the last version and use your model from figshare.

> File "/root/prosit/server.py", line 28, in predict
>    result = prediction.predict(tensor, model, model_config)
>  File "/root/prosit/prediction.py", line 14, in predict
>    model.compile(optimizer="adam", loss="mse")

 [omitted.....]

> ValueError: Tensor("out_target:0", shape=(?, ?), dtype=float32) must be from the same graph as Tensor("out/Reshape:0", shape=(?, ?), dtype=float32)

**Comment by gessulat** [comment]
I am not able to reproduce this error. Can you give me details about your system? 

Prosit needs `nvidia-docker` and CUDA installed. Then prediction should work with
`make predict DATA=/path/to/your.hdf5 MODEL=/our/model/provided/at/figshare/`
When using Prosit without `make` and Docker please make sure all dependencies are in line with the docker file.

Be sure to have the [model directory](https://github.com/kusterlab/prosit#model) has all the necessary files (model.yml, config.yml and weights.hdf5) all can be found at https://figshare.com/projects/Prosit/35582

**Comment by tobigithub** [comment]
Ff you run "make jump ..." it will not produce the 'ValueError: Tensor" error.
Its basically an issue with the current prosit makefile or prosit python scripts or prosit setups.
The current prosit version supports CUDA 9 and CUDA 10.
We are still trying to figure that out.

**Comment by gessulat** [comment]
See #8
