### ISSUE TITLE
Collision Energy Optimization

### ISSUE THREAD

**Issue by jonasfoe** [kusterlab/prosit#20]
Dear Prosit team,

I have been trying to replicate a workflow for optimizing collision energies as suggested in this presentation:
https://skyline.ms/_webdav/home/software/Skyline/events/2019%20User%20Group%20Meeting%20at%20ASMS/%40files/Presentations/02-Schmidt.pdf

The main picture for this is:
![prosit_figure](https://user-images.githubusercontent.com/9588/62370333-1d88af00-b532-11e9-8191-917159ec47df.png)
The image suggests to pick a collision energy of 28.

When I try to replicate this for an example peptide of mine, I get e.g.
![prosit_figure_ALNEKLVNL](https://user-images.githubusercontent.com/9588/62371002-f501b480-b533-11e9-9d8c-5be85910c503.png)
This might tempt me to pick an energy of 28.

When I measure empirically though, and adjust the visualization a bit, the situation looks different:
![ALNEKLVNL_nce_test](https://user-images.githubusercontent.com/9588/62371153-65a8d100-b534-11e9-84e6-03621b25e0b2.png)
Whereas strongest fragments per spectrum seem similar, it is revealed, that the absolute fragment intensities also have a strong dependence on the NCE.

The fact that Prosit only returns relative intensities makes it hard to pick the best collision energy for my work. Do you think it would be possible for Prosit to return intensities on an arbitrary scale that is somewhat comparable between spectra?

**Comment by gessulat** [comment]
Dear @jonasfoe,

thank you for digging so deep into Prosit's behavior, that graph looks interesting! :)

Mid-term, we do not think that we could build a model that can predict absolute fragment intensities, for several reasons:

1. To get best performance in the model we are using, numerically values have to be normalized between 0 and 1. We would need a re-transformation in any case to get to absolute intensities
2. Absolute intensities are dependent on various parameters many of which we do have incomplete control over. 

For example
- precursor intensity determines absolute fragment ion intensities. Either we would need to predict this too, or would need this value as input information.
- The absolute intensities are dependent on when the peptide elutes from the column. This again is dependent on your machines setup.

What you could think of, is to learn a transformation function that is specific to you data and use the relative intensities by Prosit. I am unsure if this would help in your application unfortunately.
