### ISSUE TITLE
prosit does not release memory

### ISSUE THREAD

**Issue by tobigithub** [kusterlab/prosit#21]
Hi,
after running a number of prosits and processing several fasta files I observed that a large number
of prosit docker instances still linger around. It comes to the point were other tools can not be started anymore, because there is no memory left. All the calculations are finished successfully, no errors reported, just the RAM is never cleaned up.

What would be a possible quick solution to this problem (without stopping docker)?

Thanks
Tobias

![image](https://user-images.githubusercontent.com/2569565/63983477-c0721180-ca7b-11e9-9f81-ab14bb8e0adb.png)

![image](https://user-images.githubusercontent.com/2569565/63983489-cc5dd380-ca7b-11e9-8af6-e37ef34eab14.png)

**Comment by tkschmidt** [comment]
I have no quick solution and unfortunately, we are also not running this container like that for our website.
@gessulat has the most experience with the flask server but is on vacation for the next 3 weeks, perhaps he can comment on that afterward.

**Comment by tobigithub** [comment]
@tkschmidt tnx.

**Comment by tobigithub** [comment]
So I still have the problem that my GPU is blocked and 30 Gbyte of RAM are blocked once
prosit successfully finishes its calculations. Meaning I can not use it for other external GPU compute processes and RAM is also limited.  @gessulat any ideas?

**Comment by gessulat** [comment]
We are running the Flask server within one tmux shell. Ctrl-C should close the Flask server as expected. This should stop the python interpreter, kill the tensorflow session and also release all associated memory. 

Is the memory still blocked after you shut down the flask server?

**Comment by tobigithub** [comment]
@gessulat 
I think the active windows via SSH can be closed and the service will be still active (my case).   
So actively pressing CTRL-C will end the service and also free memory. So I guess one has to keep track of the windows and services. Tnx.
