### ISSUE TITLE
Error while calibrating with msms.txt and raw file from orbitrap

### ISSUE THREAD

**Issue by TrinidadMartin** [kusterlab/prosit#26]
Hello!!!

I am trying to create my library from some DDA runs I have searched using Maxquant. So I uploaded the msms.txt and one of my raw files (I don't know exactly which one of my raw file should I pick...) and I got this error:

`WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. defaults = yaml.load(f) Using TensorFlow backend. /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dask/context.py:23: UserWarning: The dask.set_options function has been deprecated. Please use dask.config.set instead warnings.warn("The dask.set_options function has been deprecated. " /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dask/dataframe/io/csv.py:326: ParserWarning: Both a converter and dtype were specified for column Reverse - only the converter will be used head = reader(BytesIO(b_sample), **kwargs) /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dask/dataframe/io/csv.py:64: ParserWarning: Both a converter and dtype were specified for column Reverse - only the converter will be used df = reader(bio, **kwargs) WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. defaults = yaml.load(f) Using TensorFlow backend. /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dask/context.py:23: UserWarning: The dask.set_options function has been deprecated. Please use dask.config.set instead warnings.warn("The dask.set_options function has been deprecated. " /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dask/dataframe/io/csv.py:326: ParserWarning: Both a converter and dtype were specified for column Reverse - only the converter will be used head = reader(BytesIO(b_sample), **kwargs) /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dask/dataframe/io/csv.py:64: ParserWarning: Both a converter and dtype were specified for column Reverse - only the converter will be used df = reader(bio, **kwargs) /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dask/dataframe/multi.py:421: FutureWarning: 'scan_number' is both an index level and a column label. Defaulting to column, but this will raise an ambiguity error in a future version indicator=indicator) /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dask/base.py:835: UserWarning: The get= keyword has been deprecated. Please use the scheduler= keyword instead with the name of the desired scheduler like 'threads' or 'processes' warnings.warn("The get= keyword has been deprecated. " /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/dask/local.py:255: FutureWarning: 'scan_number' is both an index level and a column label. Defaulting to column, but this will raise an ambiguity error in a future version return func(*args2) Traceback (most recent call last): File "oktoberfest/annotation.py", line 28, in <module> annotated = feynman.match.augment(merged_f, "yb", 6) File "/root/.pyenv/versions/3.6.0/src/feynman/feynman/match.py", line 111, in augment matches[i] = match(row, ion_types, charge_max) File "/root/.pyenv/versions/3.6.0/src/feynman/feynman/match.py", line 74, in match forward_sum, backward_sum = get_forward_backward(row.modified_sequence[1:-1]) File "/root/.pyenv/versions/3.6.0/src/feynman/feynman/match.py", line 32, in get_forward_backward masses = [constants.AMINO_ACID[a] for a in amino_acids] File "/root/.pyenv/versions/3.6.0/src/feynman/feynman/match.py", line 32, in <listcomp> masses = [constants.AMINO_ACID[a] for a in amino_acids] KeyError: 'p' make: *** [annotation] Error 4`

Please could you help me??

Thanks a lot!!
Trini

**Comment by gessulat** [comment]
Hi Trini,

I am uncertain to which of two use cases you refer: spectral library
generation or database search result rescoring.
For creating as spectral library you need to provide a csv file with the
peptides (and their meta information).
For rescoring a 100% MaxQuant search, you need to provide an msms.txt and
the corresponding searched RAW file.

I am assuming you are interested in rescoring.

It seems there is a lower case 'p' in one of your peptide sequences. Prosit
cannot interpret this as it encodes an unmodified Proline as "P".
Please make sure that all sequences in the msms.txt adhere to Prosit's
current limitations:
"Sequences with amino acid U or O are not supported. Modifications except
"M(ox)" are not supported. Each C is treated as Cysteine with
carbamidomethylation (fixed modification in MaxQuant)."

Best,
Siegfried

**Comment by TrinidadMartin** [comment]
Hello!!

Thanks a lot! I will have a look and remove/modify those sequences.

For the spectral library generation... is there a way to create them based on the DDA runs?? I don't have a csv... And it says fasta option comming soon...

Thanks again for your super fast answer ;)
Trini

**Comment by gessulat** [comment]
Hi Trini,

unfortunately we do not offer another input method than the csv file. You
can use the sequences from an msms.txt though to create such a csv file.
In the paper we describe how we did this for all analysis in there.

The fasta option is currently delayed. I am sorry!

Cheers,
Siegfried

**Comment by TrinidadMartin** [comment]
Hi Siegfried!

No worries, I created the csv from my fasta using EncyclopeDIA and then used it into Prosit to create the library ;)

Thanks again for your answer and good luck ;)
T
