### ISSUE TITLE
Download of the human library not working

### ISSUE THREAD

**Issue by evaresio** [kusterlab/prosit#29]
Hi,

I tried to download the .dlib library for human and apparently it does not work. I tried with several browsers (Safari, Firefox and Chrome).

Anything I'm doing wrong?

BTW, the yeast library download works.

Thanks for your help and have a great WE.

Emmanuel

**Comment by tkschmidt** [comment]
Hey Emmanuel,
error on my side configuring Nginx in the correct way. It's working on our computer, but if the issue reappears reopen the issue.

**Comment by evaresio** [comment]
Hi Tobias,

Works like a charm now.

Thanks.

Emmanuel
