### ISSUE TITLE
Peaks Missing in Resulting DLIBs and Intermediate File Size Differences

### ISSUE THREAD

**Issue by nicorellius** [kusterlab/prosit#30]
Greetings, I'm from Proteome Software (creators of Scaffold software) and we've deployed Prosit to AWS and built an onsite server to generate libraries. We've been doing testing and some benchmarking, and we noticed something we can't explain: resulting `*.spectronaut` CSV files and the subsequent DLIBs generated using EncyclopeDIA are about half the size (in GB) of those generated with the same FASTAs on the Kuster lab public Prosit server. 

We looked into the resulting DLIBs and did some spot-checking, using EncyclopeDIA, and we noticed peaks in most of the spectra were missing in our onsite-generated liibraries. The total number of spectra, however, in a library generated from the Human Uniprot Reviewed FASTA, were the same for both libraries (onsite vs public Prosit server). We also noticed that the ratio of peaks missing seems to increase as we approached the end of the list (eg, spectrum 1 might be none or just one peak, eg, b1, but spectrum 1000000 might be missing several, eg, b1, b2, y3, y4, and y5, etc). 

Thoughts? Our goal is to replicate the public server results, if possible, so any clues as to what's happening would be greatly appreciated.

We have deployed Prosit with the following software:

- Ubuntu 18.04
- Docker 19.03
- Nvidia 440.36
- CUDA 10.2
- Current Prosit repo code (as of about a week ago)

We're using these [models](https://figshare.com/projects/Prosit/35582):

- Prosit - Model - Fragmentation
- Prosit - Model - iRT

Hardware:

- Aorus X390 Aorus Pro Motherboard
- Intel i9-9900K CPU
- Crucial NVMe M.2 SSD (1 TB)
- 64 GB RAM (2 x 32 GB) Crucial non-ECC un-buffered DDR4 RAM
- Zotac GeForce GTX 1080 Ti GPU, 11 GB RAM

**Comment by zerodarkzone** [comment]
Up

**Comment by nicorellius** [comment]
@LLautenbacher I'm unsure why this was closed. Was new code pushed to the repo? We are still seeing this problem, along with other reported issues. 

@zerodarkzone What does "Up" mean? Did you see this same issue?

**Comment by LLautenbacher** [comment]
My bad I thought a colleague already took care of this.
