### ISSUE TITLE
Error in building model

### ISSUE THREAD

**Issue by chinmaya-likshaka** [kusterlab/prosit#31]
Hello,

I am facing an error while running "make server MODEL_SPECTRA=/home/csbmm/chinmaya/prosit-master/Fragmentation_Model/prosit1/ MODEL_IRT=/home/csbmm/chinmaya/prosit-master/iRT_Model/" in Centos7 system. Please find the attached screenshot.

I can understand that, this error is coming from Makefile, where it is looking for a directory or file "/root/model_spectra/" which doesn't exists at all.

Does that mean, we have to create that path with a directory in the root or can we edit the Makefile with new path to build the model?

Can someone help with this?

-- Chinmaya
![Screenshot from 2019-12-12 17-32-32](https://user-images.githubusercontent.com/58813915/70712133-1c019b80-1d09-11ea-91b8-7e45482b3aad.png)

**Comment by gessulat** [comment]
Hi Chinmaya,

it looks like you made breaking changes to the Makefile. 
Prosit assumes that within the Docker container your model is at "/root/model_spectra/". 
This is what happens in: https://github.com/kusterlab/prosit/blob/master/Makefile#L18
In your case it maps your MODEL_SPECTRA folder to `/root/csbm/prosit/model_spectra`.

The easiest way to prevent this error is to revert your changes made to your Makefile (and use our default version). Another option would be to change default paths inside the code, but I would not recommend that, because it may likely break other things.

**Comment by chinmaya-likshaka** [comment]
Hi Siegfried,

I have downloaded new prosit, fragmentation and irt model files again and
stored in a new folder and ran your command to make server. But, I still
ending up with the same error.























*[root@csbmm64 prosit-master_new]# make server
MODEL_SPECTRA=fragmentation_model MODEL_IRT=irt_modelnvidia-docker build
-qf Dockerfile -t prosit .docker build -qf Dockerfile -t prosit
.sha256:c37e1069cf7ebe9fbd8fb9b0d0785750ad8ea4916dff901cbc6dff66c0bed118nvidia-docker
run -it \    -v "fragmentation_model":/root/model_spectra/ \    -v
"irt_model":/root/model_irt/ \    -e CUDA_VISIBLE_DEVICES=0 \    -p
5000:5000 \    prosit python3 -m prosit.serverdocker run --runtime=nvidia
-it -v fragmentation_model:/root/model_spectra/ -v
irt_model:/root/model_irt/ -e CUDA_VISIBLE_DEVICES=0 -p 5000:5000 prosit
python3 -m prosit.serverUsing TensorFlow backend.Traceback (most recent
call last):  File "/usr/lib/python3.5/runpy.py", line 184, in
_run_module_as_main    "__main__", mod_spec)  File
"/usr/lib/python3.5/runpy.py", line 85, in _run_code    exec(code,
run_globals)  File "/root/prosit/server.py", line 92, in <module>
trained=True  File "/root/prosit/model.py", line 37, in load    with
open(config_path, "r") as f:FileNotFoundError: [Errno 2] No such file or
directory: '/root/model_spectra/config.yml'make: *** [Makefile:17: server]
Error 1*

However, this time can see model_irt and model_spectra folders being
created inside the root by the make command which was not occurring
previously. May be because of the changes we did in the root directory.

Later, I copied all config.yml, model.yaml and weight_***.hdf5 files from
both fragmentation model and irt model folders (newly downloaded from
figshare) and pasted inside model_spectra and model_irt directories created
inside the root. Even then, the make server command is terminating with the
same error.

I am not able to fathom what exactly happening here. Please help me to
resolve the same.

-- Chinmaya

**Comment by gessulat** [comment]
Please understand that we cannot debug changes to our code that you made individually and that we don't have access to. We can only provide support for the published code as is.

Also please read and follow the steps described in the README carefully and refrain from making changes to the code or your root directory: 
1. Download the fragmentation and irt model (all files provided: config model and weight files) and save same somewhere. Let's assume the paths to those directories are `/path/to/fragmentation_model/` and `/path/to/irt_model/`, respectively. 
2. Use the make server command 
`make server MODEL_SPECTRA=/path/to/fragmentation_model/ MODEL_IRT=/path/to/irt_model/`

The error you posted states that your model_spectra folder does not include a config.yml. 
If the config.yml is in that folder with this exact name, the error will be different.

**Comment by chinmaya-likshaka** [comment]
Hi Seigfried,

As I have mentioned in my earlier email, the make server command was
showing the same error with new prosit files downloaded freshly from your
github source (Please find the attached screen shot of the error).

However, we were able to figure out that the issue was with one of the file
extension present in one of your model. And finally we are able to run the
command make server without any error.

Please check files uploaded in your model_irt_prediction folder in figshare
thoroughly (https://figshare.com/articles/Prosit_-_Model_-_iRT/6965801).
Request you to upload files with exact extensions. I hope you will be able
to figure it out.

Thanks & Regards,
Chinmaya

**Comment by mezarino** [comment]
Hello both,

the issue is that in some of the Figshare pre-trained model folders, you guys accidentally use "_model.yaml_" for the extension instead of "_model.yml_" just change that using the mv or rename command in Linux. Then rerun _make server..._ and problem solved.

Cheers!
