### ISSUE TITLE
Predicted b/y-ions with ammonia or water loss

### ISSUE THREAD

**Issue by MarcIsak** [kusterlab/prosit#32]
Hi, 

I am currently comparing my confident experimental spectra with a corresponding predicted spectra from Prosit, for the same precursor. I noticed that the spectral library that I downloaded from the web server, does not provide y/b-ions with ammonia -or water losses. I just wonder if it would be possible to include these ions in the prediction, because it would definitely improve the similarity between experimental and predicted spectra. 

I think the tool is amazing, but I just want to help you to make it even better :). 

Best,

Marc

**Comment by gessulat** [comment]
Hi Marc,
first of all thank you for giving Prosit a try and providing feedback!
Including neutral losses is on our list we want to do, but unfortunately a set of dependencies come with it. This is why I unfortunately cannot give you an estimate when we will have them available.

You might be able to find an additional experimental spectrum that can help with yours at proteomicsdb.org. I am sorry that we cannot help you with the neutral losses in Prosit at this time!

Best,
Sigi
