### ISSUE TITLE
An error occured. Status code: 2 

### ISSUE THREAD

**Issue by MS4MS** [kusterlab/prosit#33]
Hello!

Anyone can help me ? I can not understand what PROSIT is saying... I am using it directly on site and I obtain this:
"WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. Using TensorFlow backend. /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. defaults = yaml.load(f) Traceback (most recent call last): File "oktoberfest/tensor_peptidelist.py", line 23, in <module> tensor = prosit.tensorize.peptidelist(df) File "/root/.pyenv/versions/3.6.0/src/prosit/prosit/tensorize.py", line 55, in peptidelist "collision_energy_aligned_normed": get_numbers(df.collision_energy) / 100., File "/root/.pyenv/versions/3.6.0/src/prosit/prosit/tensorize.py", line 27, in get_numbers a = numpy.array(vals).astype(dtype) ValueError: could not convert string to float: '28;2' make: *** [tensor_peptidelist] Error 5"

Thanks a lot for any help !

**Comment by tkschmidt** [comment]
Hey,
it seems that you used **;** to seperate entries in your csv. We need **,**
I will try to update the error messages.

Best,
Tobias
