### ISSUE TITLE
CE calibration and rescoring

### ISSUE THREAD

**Issue by zerodarkzone** [kusterlab/prosit#34]
Hi,
Are you going to share the code used for CE calibration and RESCORING in you prosit public server?
Thanks

**Comment by tkschmidt** [comment]
Hey,
unfortunately, we can't share the code running on our public server. It is customized for our server and its interaction with ProteomicsDB and we don't have the manpower to entangle it in the upcoming future.

But,
CE calibration is quite simple. Predict for 1000 high-scoring spectra the spectra in every CE. 
Calculate for every CE the spectral angle to the 1000 raw spectra.
Select the CE with the highest spectral angle average.

**Comment by courcelm** [comment]
Hello,
I would also be interested to have access to this code, even if it is not in a functional tool. 

Particularly, I would like to have more details on how to compute the long list of Prosit features/scores to pass to Percolator.

Thanks!
