### ISSUE TITLE
Predict without Cysteine Carbamidomethylation 

### ISSUE THREAD

**Issue by jmueller95** [kusterlab/prosit#35]
Hey all,
just started using the local version of Prosit - very exciting tool, thank you!
Is there a way to switch off the fixed Carbamidomethylation modification of Cysteines? I would like to use Prosit for some samples in which Cysteine was not treated with iodoacetamide. 

Best wishes,
Julian 

PS: I also noticed the precursor m/zs do not seem to account for the Carbamidomethylation. This has already been reported for the online version of the tool, I made a comment in the respective issue (#13).

**Comment by tkschmidt** [comment]
We have no clue what the modification does exactly to the fragmentation pattern. As we have no non-modified Cysteines we have no training data -> no way to train/validate.

**Comment by jmueller95** [comment]
Ok, thank you!
