### ISSUE TITLE
Error log 2

### ISSUE THREAD

**Issue by MS4MS** [kusterlab/prosit#38]
Hey !

I am back with some trouble using prosit... How I have tot interpretate this ?
An error occured. Status code: 2 
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. Traceback (most recent call last): File "oktoberfest/grpc_predict_peptidelist.py", line 36, in <module> disable_progress_bar=True) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/predictPROSIT.py", line 153, in predict_to_hdf5 models=[irt_model, intensity_model]) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/predictPROSIT.py", line 123, in predict self.input.prepare_input(disable_progress_bar) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/inputPROSIT.py", line 15, in prepare_input self.sequences.prepare_sequences(flag_disable_progress_bar) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/inputPROSIT.py", line 143, in prepare_sequences self.character_to_array(flag_disable_progress_bar) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/inputPROSIT.py", line 118, in character_to_array total=len(self.character)): File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tqdm/std.py", line 1107, in __iter__ for obj in iterable: File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/__utils__.py", line 88, in split_modstring raise ValueError(f"Unknown Element in string: {sequence}. Found Elements: {x}") NameError: name 'x' is not defined make: *** [grpc_predict] Error 8

**Comment by fburic** [comment]
I believe this is due to the presence of an unsupported amino acid in the Prosit input file (specifically, 'X' if I'm reading the error message right.).

You could try cleaning the input file to remove any sequences with unsupported amino acids. Or, if you're comfortable with Python, I suggested a fix here: https://github.com/kusterlab/prosit/issues/41

**Comment by LLautenbacher** [comment]
Hi,

@fburic is partially correct There is some unsupported amino acid or modification in the input file. Sadly the x has nothing to do with the faulty amino acid. It comes from a bug that is fixed already and will be online soon.

We support only the 20 standard AA and oxidized methionine represented in the sequence as M(ox).

Best,
Ludwig
