### ISSUE TITLE
Issues with the web server for predictions?

### ISSUE THREAD

**Issue by MarcIsak** [kusterlab/prosit#43]
Hi,

I submitted a small CSV file (~20 000 precursors) for prediction of MS/MS and RT to the Prosit web server. The job is somehow still in process though it has been > 36 hours since submission. 

I just wonder if there are any issues with the server right now? I have never experienced these waiting times before, even if I have submitted csv files with > 1 000 000 precursors for prediction. 

Best,

Marc

**Comment by LLautenbacher** [comment]
Hi Marc,

you are right there were some issues with the Prosit web server. They should be fixed now. Check your Job again it might be done already.

Best,
Ludwig

**Comment by MarcIsak** [comment]
Thanks for the quick reply!

I just downloaded the data, so yes it seems to work now :-). 

Best,

Marc
