### ISSUE TITLE
Error when creating a Prosit predicted library

### ISSUE THREAD

**Issue by jacoblippincott** [kusterlab/prosit#47]
What happened: I uploaded a CSV file generated using EncyclopeDIA to create a predicted library. I got the error shown in the image below. 

What should have happened: I expected a predicted library to be exported in the .CSV format. 

Steps to reproduce: I can provide the file if needed. Basically, try to generate a lib using the CSV file using the 2019 model and export as a CSV file. 
![prosit_error](https://user-images.githubusercontent.com/58231761/96038509-1474bc80-0e1c-11eb-8417-9f57a28d44de.png)

**Comment by MarcIsak** [comment]
Hi,

I got the same error message for the files I uploaded yesterday, so it is definitely a reproducible error. I selected the 2019 iRT model and the 2020 intensity model, and as output I selected the generic text format. It is the first time I encounter this kind of error.

**Comment by LLautenbacher** [comment]
Hi,

we are currently working on an update of Prosit and in the process of this, we accidentally deployed an unstable version.  We reset Prosit and restarted all jobs that were affected by this. You can check again to see if your Prosit jobs are done yet!

Best,
Ludwig

**Comment by MarcIsak** [comment]
Great!

thank you for getting back so quickly regarding this matter! Prosit is a great tool btw!

Best,

Marc

**Comment by jacoblippincott** [comment]
Tried to process the same file again using the same workflow. Got this error instead
![prosit_2](https://user-images.githubusercontent.com/58231761/96285314-a521d880-0f93-11eb-8c07-77a3a305ceb1.png)

**Comment by MarcIsak** [comment]
Same error here after the restart of jobs...

**Comment by LLautenbacher** [comment]
Hi MarcIsak,

when you give me your Task-ID I can check what went wrong!

Best,
Ludwig

**Comment by MarcIsak** [comment]
Hi LLautenbacher, 

you can get the following task-ID from me:

_B6084FB8E791AD3F9FC1E346C44BEC26_

Best,

Marc

**Comment by LLautenbacher** [comment]
We currently have a issue with the spectronaut output for very big input files.Both of your jobs ran into this issue. If you split your input across multiple jobs it should work. 830.000 spectra is currently confirmed to work.

Alternatively if you can also use a different output format both dlib and msp can handle bigger outputs and are generated much quicker.

**Comment by MarcIsak** [comment]
Hi,

I see...in this case I will consider splitting the files into several jobs. Unfortunately, I need to use the Spectronaut format for my particular application. 

Thanks again for the quick response!

Best,

Marc
