### ISSUE TITLE
How to add other fixed motification except for  Cysteine with carbamidomethylation？

### ISSUE THREAD

**Issue by xiangrong7** [kusterlab/prosit#50]
Dear developers,
Thank you for developing this tools.
I generated a spectral library by predicting a list of peptides given in a CSV file. I noticed each C is treated as Cysteine with carbamidomethylation and oxidized Methionine with "M(ox)". How about  TMT modification (K, +229; N-terminus, +229 )? Can I add other motifications?

**Comment by LLautenbacher** [comment]
Hi,
because our training data only included oxidized Methionine and carbamidomethylated Cysteine we currenlty only support these modifications. But we are working on extending Prosit to other modifications.
