### ISSUE TITLE
An error occured so many times when I try to use Prosit to predict spectrum library.So I need your help!

### ISSUE THREAD

**Issue by Clovernana** [kusterlab/prosit#52]
Hi ,
Thank you for your good job!
I have read the article”Generating high quality libraries for DIA MS with empirically corrected peptide predictions ”.And I’m very interested to this project.And I want to predict a library as the article discribed.But ,maybe due to my poor computer setup,I have tried to run **Prosit** for many times but all failed.So I want to ask for your help to run this .csv file for me and send me the 
 results bu email 16622080827@163.com

[Swissprot_human_20200929_reviewed_20375.fasta.trypsin.z3_nce33.zip](https://github.com/kusterlab/prosit/files/5642577/Swissprot_human_20200929_reviewed_20375.fasta.trypsin.z3_nce33.zip)

.Could you plesase help me ?I’m really sorry to trouble you.

I have uploaded the input file for prosit in the attachment.

Here is the error log:

Error logkeyboard_arrow_downWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. defaults = yaml.load(f) Using TensorFlow backend. Process Process-2: Traceback (most recent call last): File "/root/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap self.run() File "/root/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/process.py", line 93, in run self._target(*self._args, **self._kwargs) File "/root/.pyenv/versions/3.6.0/src/converter/converter/spectronaut_conv/converter.py", line 148, in to_csv for spectrum in converted: File "/root/.pyenv/versions/3.6.0/src/converter/converter/spectronaut_conv/converter.py", line 136, in get_converted x = self.queue.get() File "<string>", line 2, in get File "/root/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/managers.py", line 757, in _callmethod kind, result = conn.recv() File "/root/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/connection.py", line 250, in recv buf = self._recv_bytes() File "/root/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes buf = self._recv(4) File "/root/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/connection.py", line 379, in _recv chunk = read(handle, remaining) ConnectionResetError: [Errno 104] Connection reset by peer Traceback (most recent call last): File "oktoberfest/convert.py", line 20, in <module> converter.iter_data() File "/root/.pyenv/versions/3.6.0/src/converter/converter/spectronaut_conv/converter.py", line 34, in iter_data conv.convert(pool) File "/root/.pyenv/versions/3.6.0/src/converter/converter/spectronaut_conv/converter.py", line 129, in convert self.queue.put(s) File "<string>", line 2, in put File "/root/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/managers.py", line 756, in _callmethod conn.send((self._id, methodname, args, kwds)) File "/root/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/connection.py", line 206, in send self._send_bytes(_ForkingPickler.dumps(obj)) File "/root/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes self._send(header + buf) File "/root/.pyenv/versions/3.6.0/lib/python3.6/multiprocessing/connection.py", line 368, in _send n = write(self._handle, buf) BrokenPipeError: [Errno 32] Broken pipe make: *** [create_output] Error 9

**Comment by LLautenbacher** [comment]
Hi,

this error is caused if the generated spectronaut file is too large. We already fixed this bug, it will be applied with the next update to prosit.
For now, you can circumvent this error by splitting your input over multiple files (800 000 spectra is currently the maximum confirmed to work) or select a different output than spectronaut.

Best,
Ludwig

**Comment by Clovernana** [comment]
OK，I will try it.

**Comment by Clovernana** [comment]
Hi,Ludwig
I have tried different outputs in prosit.But the protein names are described as "unkonw" in the  library.And ths imapcts identification  severely. Do you have any idea about it?

Best wishes,
Clover
