### ISSUE TITLE
HEK293 specific fasta file?

### ISSUE THREAD

**Issue by Clovernana** [kusterlab/prosit#53]
Hi,
Thank you for your good job!
Is there any HEK293 specific fasta file or .dlib format spectra library file (predicted by prosit)?I have noticed that there are some predicted libraries here.But I need HEK293 specific libraries.
![image](https://user-images.githubusercontent.com/50875585/101911947-0ebd0c80-3bfc-11eb-850e-7cf5b9bf882b.png)

**Comment by tkschmidt** [comment]
Hi,
these are just the supporting libraries for Brian searles paper. We do not provide full blown libraries as it is recommended to do first an CE alignment to find optimal settings for your workflow.

If we would store a library for every organism and every collision energy, we would quickly run out of storage.
