### ISSUE TITLE
output format

### ISSUE THREAD

**Issue by im281** [kusterlab/prosit#55]
Web server says it supports *.dlib but is the code udpdated? Don't see any *.dlib output examples

**Comment by LLautenbacher** [comment]
Hi,

in the last step of the spectral library job, you can choose which output you want to generate:

![image](https://user-images.githubusercontent.com/59884643/103994366-32da2200-5197-11eb-9c5a-eca54118907c.png)

**Comment by im281** [comment]
yes I see it on the web server but when I deploy the server myself from source there are no options for *dlib output
