### ISSUE TITLE
Found Elements: {x}") NameError: name 'x' is not defined make: *** [grpc_predict] Error 8

### ISSUE THREAD

**Issue by MS4MS** [kusterlab/prosit#56]
Hello,

I obtain this error message but I do not understand the mining of this message. I do not have any X in my file except M(ox) and there are not unsupported amino acids. What can I do ? 
Thanks a lot for your help !

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. Traceback (most recent call last): File "oktoberfest/grpc_predict_peptidelist.py", line 36, in <module> disable_progress_bar=True) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/predictPROSIT.py", line 153, in predict_to_hdf5 models=[irt_model, intensity_model]) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/predictPROSIT.py", line 123, in predict self.input.prepare_input(disable_progress_bar) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/inputPROSIT.py", line 15, in prepare_input self.sequences.prepare_sequences(flag_disable_progress_bar) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/inputPROSIT.py", line 143, in prepare_sequences self.character_to_array(flag_disable_progress_bar) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/inputPROSIT.py", line 118, in character_to_array total=len(self.character)): File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tqdm/std.py", line 1107, in __iter__ for obj in iterable: File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/__utils__.py", line 88, in split_modstring raise ValueError(f"Unknown Element in string: {sequence}. Found Elements: {x}") NameError: name 'x' is not defined make: *** [grpc_predict] Error 8

**Comment by LLautenbacher** [comment]
Hi,
this error message means that you have some kind of unknown amino acid in your file. It doesn't have to include "x".

**Comment by MS4MS** [comment]
Ok but I searched for O or U and I do not have these amino acids

**Comment by LLautenbacher** [comment]
If you let me know your task-id I can take a look for you.

**Comment by MS4MS** [comment]
E11055D4780B108B3A39C25C1A4BB3D5

Thanks !

**Comment by LLautenbacher** [comment]
The X in `VYGFCLLLFXLNFLVVALLTEFGVIHLK` can't be parsed.

And the last two entries in your file have an empty space behind the sequence.
The entry looks like this:
`GPLKKSNAPLVNVTLYYEALCGGCR ,28,2`
But should look like this:
`GPLKKSNAPLVNVTLYYEALCGGCR,28,2`

**Comment by MS4MS** [comment]
Ooh sorry , thanks a lot !
