### ISSUE TITLE
Prosit error : server proteomicsdb.org:8500 unavailable with Skyline

### ISSUE THREAD

**Issue by MS4MS** [kusterlab/prosit#62]
Hello,

When I am trying to build my library directly in Skyline, there is an error message, the server is unavailable :
What can I do ?
---------------------------
Skyline
---------------------------
Status(StatusCode=Unavailable, Detail="failed to connect to all addresses")
---------------------------
OK More Info
---------------------------
pwiz.Skyline.Model.Prosit.PrositException: Status(StatusCode=Unavailable, Detail="failed to connect to all addresses") ---> Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="failed to connect to all addresses")
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   à Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   à Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   à Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   à Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   à Tensorflow.Serving.PredictionService.PredictionServiceClient.Predict(PredictRequest request, CallOptions options) dans C:\proj\skyline_20_2_x64\pwiz_tools\Skyline\ProtocolBuffers\GeneratedCode\PredictionServiceGrpc.cs:ligne 96
   à Tensorflow.Serving.PredictionService.PredictionServiceClient.Predict(PredictRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) dans C:\proj\skyline_20_2_x64\pwiz_tools\Skyline\ProtocolBuffers\GeneratedCode\PredictionServiceGrpc.cs:ligne 86
   à pwiz.Skyline.Model.Prosit.Models.PrositModel`6.Predict(PredictionServiceClient predictionClient, TPrositIn inputData, CancellationToken token) dans C:\proj\skyline_20_2_x64\pwiz_tools\Skyline\Model\Prosit\Models\PrositModel.cs:ligne 230
   --- Fin de la trace de la pile d'exception interne ---
   à pwiz.Skyline.Model.Prosit.Models.PrositModel`6.Predict(PredictionServiceClient predictionClient, TPrositIn inputData, CancellationToken token) dans C:\proj\skyline_20_2_x64\pwiz_tools\Skyline\Model\Prosit\Models\PrositModel.cs:ligne 234
   à pwiz.Skyline.Model.Prosit.Models.PrositModel`6.PredictBatches(PredictionServiceClient predictionClient, IProgressMonitor progressMonitor, IProgressStatus& progressStatus, SrmSettings settings, IList`1 inputs, CancellationToken token) dans C:\proj\skyline_20_2_x64\pwiz_tools\Skyline\Model\Prosit\Models\PrositModel.cs:ligne 314
   à pwiz.Skyline.Model.Prosit.PrositLibraryBuilder.BuildLibraryOrThrow(IProgressMonitor progress, IProgressStatus& progressStatus) dans C:\proj\skyline_20_2_x64\pwiz_tools\Skyline\Model\Prosit\PrositLibraryBuilder.cs:ligne 112
   à pwiz.Skyline.Model.Prosit.PrositLibraryBuilder.BuildLibrary(IProgressMonitor progress) dans C:\proj\skyline_20_2_x64\pwiz_tools\Skyline\Model\Prosit\PrositLibraryBuilder.cs:ligne 68
---------------------------

**Comment by LLautenbacher** [comment]
Hi, 

the prosit server is online and available and with the newest skyline version (20.2.0.343) I cannot replicate your issue. I think you are already in contact with the skyline team. They should be able to resolve this issue for you.

Best,
Ludwig
