### ISSUE TITLE
Error in online version

### ISSUE THREAD

**Issue by bjgprt** [kusterlab/prosit#63]
In predicting Spectral Library, what is the limit of the csv file, please? I have tested with a file with 25 lines and it worked. However, when I tried larger files (>600000, less than 50M) it is always failed. Thanks!

Task AC6F33D04A4E553E95576D3D6DC9480D
An error occured. Status code: 2
Error log
keyboard_arrow_down
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. Traceback (most recent call last): File "oktoberfest/grpc_predict_peptidelist.py", line 36, in <module> disable_progress_bar=True) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/predictPROSIT.py", line 153, in predict_to_hdf5 models=[irt_model, intensity_model]) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/predictPROSIT.py", line 133, in predict pred_object.predict(disable_progress_bar) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/PredObject.py", line 116, in predict disable_progress_bar=disable_progress_bar) File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/PredObject.py", line 101, in send_requests total=n_batches): File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/tqdm/std.py", line 1107, in __iter__ for obj in iterable: File "/root/.pyenv/versions/3.6.0/src/prosit-grpc/prosit_grpc/PredObject.py", line 66, in create_requests assert len(i) == len(j) TypeError: object of type 'NoneType' has no len() make: *** [grpc_predict] Error 8

**Comment by LLautenbacher** [comment]
Hi, your last entry is missing collision_energy and precursor_charge.
