### ISSUE TITLE
API for Prosit predictions

### ISSUE THREAD

**Issue by MarcIsak** [kusterlab/prosit#64]
Hello, 

I wonder if it is possible to use some sort of API to send / retrieve jobs from the Prosit server(s)? That would make my life much easier when submitting several jobs ;). 

Thank you for the amazing Prosit tool!

Best,

Marc

**Comment by LLautenbacher** [comment]
Hi Marc,

we do not offer and do not plan an API for Prosit since our server-infrastructure would not be able to handle the number of requests we expect to get.

I am sorry for not being able to help you more with this.

Best,
Ludwig
