### ISSUE TITLE
Modifications in non-tryptic data

### ISSUE THREAD

**Issue by kevinkovalchik** [kusterlab/prosit#67]
Hello,

I am very interested in the non-tryptic model, but I am unsure of the modifications present in the training data. Is it the same as the tryptic data? i.e. CAM and ox(M)?

Thanks!
Kevin

**Comment by courcelm** [comment]
I had the same question in mind. For MHC, it is not common to use carbamidomethylation. Is C treated as CAM in this model?

**Comment by LLautenbacher** [comment]
Yes, all our models are using carbamidomethylation as a fixed modification.
