### ISSUE TITLE
Server down? 

### ISSUE THREAD

**Issue by MarcIsak** [kusterlab/prosit#69]
Hi, I submitted some smaller tasks to the online Prosit prediction tool a few days ago and they are still not ready. Just would like to check with you if the server is down? 

Best,

**Comment by LLautenbacher** [comment]
Hi, I restarted the server, your Job should be done by now. 
If you have any other issues, please let me know.

Best,
Ludwig

**Comment by MarcIsak** [comment]
Thanks!
