### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by MarcIsak** [kusterlab/prosit#70]
Hi, just wondering if the server is down? I submitted a CE Calibration work several hours ago and it is still not ready. Typically, this process is very quick. 

Best,

Marc

**Comment by MarcIsak** [comment]
Still not completed yet. Any news on the server. 

Thanks in advance!

Marc

**Comment by WassimG** [comment]
we restarted the server try to run your job again.

**Comment by MarcIsak** [comment]
Ok, so the already submitted jobs will be lost?

**Comment by WassimG** [comment]
if it ran and you didn't get a result you need to re-run it yes

**Comment by MarcIsak** [comment]
Thanks it works now!
