### ISSUE TITLE
Prosit's dependencies incompatible with institute HPC's security policy 

### ISSUE THREAD

**Issue by BenSamy2020** [kusterlab/prosit#71]
Greetings,

Firstly, I would like to thank you for provided a amazing open-source tool. Specifically, I was interested in generating spectral library from a list of peptides using Prosit. Unfortunately, the generated Prosit compatible CSV file is >50 MB (file size 350 MB). Therefore the generated file could not be uploaded and spectral library could not be generated using the web-server option.

I understand that Prosit can be ran on command line. Due to my institute security policy, I am not able to run Prosit on my institutes HPC. Collectively, I have tried multiple options to utilize your software.

Is there a way to by-pass the file size limit or could we collaborate to generate the spectral library using Prosit prediction?

Regards,
Ben

**Comment by LLautenbacher** [comment]
Hi Ben,

you can split the input CSV into multiple parts, upload them separately, and combine the result files. 

Best,
Ludwig
