### ISSUE TITLE
Error occured. Status code: 2 

### ISSUE THREAD

**Issue by phil812** [kusterlab/prosit#75]
Good day,

I try predict a spectral library for Wheat, which is too large (> 300 MB) for directly uploading it into the Prosit web version, so I split the large csv. file into smaller csv. files. I tried to upload some of them and for quite a number of samples it worked, however for a few I get the following error code:

Task 24B4804E9EEA5BB4AF6F2C0C9EB079B9
An error occured. Status code: 2
    Error log
    keyboard_arrow_down
    WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. Traceback (most recent call last): File "/root/.pyenv/versions/3.6.2/lib/python3.6/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/root/.pyenv/versions/3.6.2/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/root/oktoberfest/library/grpc_predict_peptidelist.py", line 44, in <module> disable_progress_bar=True) File "/root/.pyenv/versions/3.6.2/src/prosit-grpc/prosit_grpc/predictPROSIT.py", line 157, in predict_to_hdf5 models=[irt_model, intensity_model, proteotypicicty_model]) File "/root/.pyenv/versions/3.6.2/src/prosit-grpc/prosit_grpc/predictPROSIT.py", line 127, in predict self.input.prepare_input(disable_progress_bar) File "/root/.pyenv/versions/3.6.2/src/prosit-grpc/prosit_grpc/inputPROSIT.py", line 15, in prepare_input self.sequences.prepare_sequences(flag_disable_progress_bar) File "/root/.pyenv/versions/3.6.2/src/prosit-grpc/prosit_grpc/inputPROSIT.py", line 147, in prepare_sequences self.character_to_array(flag_disable_progress_bar, filter=filter) File "/root/.pyenv/versions/3.6.2/src/prosit-grpc/prosit_grpc/inputPROSIT.py", line 118, in character_to_array total=len(self.character)): File "/root/.pyenv/versions/3.6.2/lib/python3.6/site-packages/tqdm/std.py", line 1149, in __iter__ for obj in iterable: File "/root/.pyenv/versions/3.6.2/src/prosit-grpc/prosit_grpc/__utils__.py", line 94, in split_modstring raise ValueError(f"The element(s) [{not_parsable_elements}] " ValueError: The element(s) [X] in the sequence [LXRLSSR] could not be parsed make: *** [grpc_predict] Error 8

I’m really sorry to bother you, but could you please help me with my problems?

**Comment by fchu763** [comment]
Hello,

I have uploaded a csv file approximately 40 MB in size and have received a similar error for my spectral prediction run. 

The task ID is 2B1563C65BA1AA76E2B951AF191E07BA and here is the error message:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. /root/.pyenv/versions/3.6.2/lib/python3.6/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. defaults = yaml.load(f) Using TensorFlow backend. Process Process-2: Traceback (most recent call last): File "/root/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap self.run() File "/root/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/process.py", line 93, in run self._target(*self._args, **self._kwargs) File "/root/.pyenv/versions/3.6.2/src/converter/converter/spectronaut_conv/converter.py", line 150, in to_csv for spectrum in converted: File "/root/.pyenv/versions/3.6.2/src/converter/converter/spectronaut_conv/converter.py", line 138, in get_converted x = self.queue.get() File "<string>", line 2, in get File "/root/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/managers.py", line 757, in _callmethod kind, result = conn.recv() File "/root/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/connection.py", line 250, in recv buf = self._recv_bytes() File "/root/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes buf = self._recv(4) File "/root/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/connection.py", line 383, in _recv raise EOFError EOFError Traceback (most recent call last): File "/root/.pyenv/versions/3.6.2/lib/python3.6/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/root/.pyenv/versions/3.6.2/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/root/oktoberfest/library/convert.py", line 24, in <module> converter.iter_data() File "/root/.pyenv/versions/3.6.2/src/converter/converter/spectronaut_conv/converter.py", line 34, in iter_data conv.convert(pool) File "/root/.pyenv/versions/3.6.2/src/converter/converter/spectronaut_conv/converter.py", line 131, in convert self.queue.put(s) File "<string>", line 2, in put File "/root/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/managers.py", line 756, in _callmethod conn.send((self._id, methodname, args, kwds)) File "/root/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/connection.py", line 206, in send self._send_bytes(_ForkingPickler.dumps(obj)) File "/root/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes self._send(header + buf) File "/root/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/connection.py", line 368, in _send n = write(self._handle, buf) BrokenPipeError: [Errno 32] Broken pipe make: *** [create_output] Error 9

Any help with this issue would be greatly appreciated!

**Comment by WassimG** [comment]
Hi Phil,

Your error is happening because of X in the peptide sequence, I am not sure what this means here exactly (I guess it's unknown or it could be any amino acid) and we don't support this in our input. 

Thanks

**Comment by WassimG** [comment]
Hi fchu,

No it's a different error it's not clear exactly what from the error message will check your task and let you know

**Comment by AmandaBaldassi** [comment]
Hi,

I have uploaded a csv file approximately 47 MB in size and have received a similar error for my spectral prediction run.

The task ID 54567DA946E3FE90171CFC8BA6B75D89 and here is the error message: ERROR LOG STATUS CODE:2

Could you help me?

Thanks,
Amanda

**Comment by WassimG** [comment]
Hi fchu and Amanda,

We had a problem with the server fixed now please re-submit your tasks.

Thanks

**Comment by AmandaBaldassi** [comment]
Hi,

I tried yesterday again and I had the same problem.

My task number is: FC5C49B733B3FA13508E90389A8397DA

Could you see what happened?

Thanks,
Amanda

Em sáb., 13 de nov. de 2021 às 02:33, WassimG ***@***.***>
escreveu:
