### ISSUE TITLE
Expected time for job completion on server, and related feature request

### ISSUE THREAD

**Issue by yangkl96** [kusterlab/prosit#78]
Hello,

I submitted two jobs yesterday to the Prosit server. It has been around 24 hours but they have not completed yet. How long can I typically expect it to take for a job to complete?

On a related note, would it be possible for the webpage to update with how many jobs are before mine in the queue?

Thanks,
Kevin

**Comment by yangkl96** [comment]
AD9D0EDADF1BEA157EFCEEFEFC608608 and A935DEDA956F184C3761E7A24E239F40

**Comment by yangkl96** [comment]
My first job failed with the following error log. Could you explain what the issue was here?

`2022-01-20 14:23:49.127235: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory 2022-01-20 14:23:49.127267: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine. /root/oktoberfest/spectral_library.py:94: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame. Try using .loc[row_indexer,col_indexer] = value instead See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy library.spectra_data['GRPC_SEQUENCE'] = library.spectra_data['MODIFIED_SEQUENCE'] 2022-01-20 14:23:53,986 - ERROR - oktoberfest.spectral_library::grpc_predict An exception was thrown! Traceback (most recent call last): File "/root/oktoberfest/spectral_library.py", line 96, in grpc_predict predictions,sequences = predictor.predict(sequences=library.spectra_data["GRPC_SEQUENCE"].values.tolist(), File "/usr/local/lib/python3.8/site-packages/prosit_grpc/predictPROSIT.py", line 152, in predict pred_object.predict(disable_progress_bar) AttributeError: 'NoneType' object has no attribute 'predict' Traceback (most recent call last): File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/root/oktoberfest/__main__.py", line 8, in <module> main() File "/root/oktoberfest/oktoberfest.py", line 35, in main run_oktoberfest(args.search_dir, args.config_path) File "/root/oktoberfest/oktoberfest.py", line 160, in run_oktoberfest generate_spectral_lib(search_dir, config_path) File "/root/oktoberfest/oktoberfest.py", line 104, in generate_spectral_lib grpc_output_sec = spec_library.grpc_predict(spectra_div) File "/root/oktoberfest/spectral_library.py", line 107, in grpc_predict return predictions UnboundLocalError: local variable 'predictions' referenced before assignment make: *** [/oktoberfest/Makefile:23: run_oktoberfest] Error 2`

**Comment by WassimG** [comment]
Hey Kevin,

it was a bug on our site, now both of your tasks are done as well.

**Comment by yangkl96** [comment]
Just downloaded and they look good. Thank you
