### ISSUE TITLE
MSP files "Num peaks" always reporting 174 peaks

### ISSUE THREAD

**Issue by yangkl96** [kusterlab/prosit#79]
Hello,

The peptides in the prediction files from the web server always report `Num peaks: 174` even when most of them are shorter. For example, this is the beginning of my downloade msp file. 
[examplePrositLib.txt](https://github.com/kusterlab/prosit/files/7915747/examplePrositLib.txt)

174 peaks are reported in my other downloaded file as well. Is this a mistake?

**Comment by WassimG** [comment]
Hello,

it was an issue on our side it got fixed now, resubmit the jobs and it would work correctly now.

**Comment by yangkl96** [comment]
Thank you, it works as a csv
