### ISSUE TITLE
Unable to download spectral library

### ISSUE THREAD

**Issue by LeeSCantrell** [kusterlab/prosit#88]
Hi all,
Hopefully a basic question. I am unable to download the following taskID 074DE794AC453D061CC8AEE94D7FA0FB 

I have tried multiple computers/web browsers in and out of private mode. 

Please advise. 

Thanks, 
Lee

**Comment by LLautenbacher** [comment]
Hi,

this error happens because the file you uploaded is too large. Split your file across multiple jobs such that each job has no more than 800k entries.

Best,
Ludwig
