### ISSUE TITLE
handling of uncommon amino acids

### ISSUE THREAD

**Issue by tobigithub** [kusterlab/prosit#9]
The human fasta file has around 3447 occurrences of "X" or "uncommon amino acids".
They are not defined in prosit/prosit/constants.py

The code actually should either ignore or define them or use proper error handling when X is observed. Currently the code just breaks with **KeyError: 'X'** This would increase robustness of the code.

```
    tensor = tensorize.peptidelist(df)
  File "/root/prosit/tensorize.py", line 56, in peptidelist
    "sequence_integer": get_sequence_integer(df.modified_sequence),
  File "/root/prosit/tensorize.py", line 42, in get_sequence_integer
    array[i, j] = constants.ALPHABET[s]
KeyError: 'X'
```

**Comment by gessulat** [comment]
We do not filter user input on purpose, as this would change the expected number of predicted psms.
I updated the Readme to clearify which amino acids are supported. https://github.com/kusterlab/prosit/blob/master/README.md#using-prosit-on-your-data

**Comment by tobigithub** [comment]
@gessulat 
Tnx!
