### ISSUE TITLE
Prosit Download showing server issues

### ISSUE THREAD

**Issue by subinamehta** [kusterlab/prosit#91]
{"error":"Error: HttpClient.getResponse: Can't get the response from the server: IPCon error: \"Connection to 131.159.152.7 lost while reading response.\""}

**Comment by BenSamy2020** [comment]
Greetings @tkschmidt,

I am also facing a similar issue - {"error":"Error: HttpClient.getResponse: Can't get the response from the server: IPCon error: \"Connection to 131.159.152.7 lost while reading response.\""}

Please do advise me on how to download my data. Lastly, thank you in advance for your assistance. 

Regards,
Ben

**Comment by WassimG** [comment]
Hey Ben and Subina,

This is usually due to issues with the size of the downloadable file if it's bigger than 2 GB, this process would fail.
Try splitting your input this should help with this issue.

Best,
Wassim
