### ISSUE TITLE
Error with spectral prediction

### ISSUE THREAD

**Issue by yangkl96** [kusterlab/prosit#93]
Hi Prosit team,

I had an error with my task B410B9EDFBBE9FA9CFEF2C8112029439. I thought there might be an issue with PTMs since I saw `sequences = predictor.predict(sequences=library.spectra_data["MODIFIED_SEQUENCE"].values.tolist()`, but I checked my input and the only PTM is M(ox). Is there something I can change about the input?

Thanks,
Kevin

**Comment by WassimG** [comment]
Hey Kevin,

No, the predictions just stopped midway .. restarted your job, and it is done now. Though the zip file is too big, you might not be able to download it. If this is the case, split the csv file with a max of 2 mil. peptide/charge combination per file.

Best,
Wassim
